steps:
  - name: vizzu/vizzu-devenv:v0.8.x
    args:
      - mkdir
      - '-p'
      - /workspace/build/cmake-desktop
    id: desktop_mkdirBuildFolder
    waitFor:
      - '-'
  - name: vizzu/vizzu-devenv:v0.8.x
    args:
      - cmake
      - -DCMAKE_BUILD_TYPE="Debug"
      - -Dclangtidy:BOOL="ON"
      - ../../project/cmake/
    dir: /workspace/build/cmake-desktop
    id: desktop_cmake
    waitFor:
      - desktop_mkdirBuildFolder
  - name: vizzu/vizzu-devenv:v0.8.x
    args:
      - cmake
      - --build
      - .
      - --target
      - cvizzu
      - vizzutest
    dir: /workspace/build/cmake-desktop
    id: desktop_make
    waitFor:
      - desktop_cmake
    timeout: 1800s
    options:
      machineType: E2_HIGHCPU_16
  - name: vizzu/vizzu-devenv:v0.8.x
    args:
      - ./vizzutest
    dir: /workspace/build/cmake-desktop/test
    id: test_desktopUnit
    waitFor:
      - desktop_make
  - name: vizzu/vizzu-devenv:v0.8.x
    args:
      - mkdir
      - '-p'
      - /workspace/build/cmake-wasm
    id: wasm_mkdirBuildFolder
    waitFor:
      - '-'
  - name: vizzu/vizzu-devenv:v0.8.x
    args:
      - '-c'
      - |-
        source "/root/emsdk/emsdk_env.sh" && emcmake cmake ../../project/cmake/
    dir: /workspace/build/cmake-wasm
    id: wasm_cmake
    waitFor:
      - wasm_mkdirBuildFolder
    entrypoint: bash
  - name: vizzu/vizzu-devenv:v0.8.x
    args:
      - cmake
      - --build
      - .
    dir: /workspace/build/cmake-wasm
    id: wasm_make
    waitFor:
      - wasm_cmake
    timeout: 1800s
  - name: vizzu/vizzu-devenv:v0.8.x
    args:
      - node
      - vizzutest.js
    dir: /workspace/build/cmake-wasm/test
    id: test_wasmUnit
    waitFor:
      - wasm_make
  - name: vizzu/vizzu-devenv:v0.8.x
    args:
      - npm
      - install
    dir: /workspace/project/js
    id: wasm_js_npmInstall
    waitFor:
      - wasm_make
  - name: vizzu/vizzu-devenv:v0.8.x
    args:
      - npm
      - run
      - build
    dir: /workspace/project/js
    id: wasm_js_npmRunBuild
    waitFor:
      - wasm_js_npmInstall
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--build-arg'
      - 'TAG=v0.8.x'
      - '-t'
      - 'gcr.io/vizzu-ci/github.com/vizzuhq/vizzu-jsunittest-cloudbuild:$BRANCH_NAME'
      - '-f'
      - ./ci/docker/vizzu-jsunittest-cloudbuild
      - .
    id: test_jsUnit
    waitFor:
      - wasm_js_npmRunBuild
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--build-arg'
      - 'TAG=v0.8.x'
      - '-t'
      - 'gcr.io/vizzu-ci/github.com/vizzuhq/vizzu-test-cloudbuild:$BRANCH_NAME'
      - '-f'
      - ./ci/docker/vizzu-test-cloudbuild
      - .
    id: test_integration
    waitFor:
      - test_jsUnit
      - test_desktopUnit
      - test_wasmUnit
  - name: vizzu/vizzu-devenv:v0.8.x
    args:
      - '-c'
      - |-
        if [ $BRANCH_NAME == "main" ]
        then
          echo $SHORT_SHA > sha.txt
        fi
    dir: /workspace/example
    id: sha_generate
    waitFor:
      - test_integration
    entrypoint: bash
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-c'
      - |-
        if [ $BRANCH_NAME == "main" ]
        then
          gsutil -m cp '/workspace/example/sha.txt' 'gs://vizzu-lib-main/lib'
        fi
    id: sha_upload
    waitFor:
      - sha_generate
    entrypoint: bash
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-c'
      - |-
        if [ $BRANCH_NAME == "main" ]
        then
          gsutil -m cp -r '/workspace/example/lib/*' 'gs://vizzu-lib-main/lib'
        fi
    id: lib_upload
    waitFor:
      - test_integration
    entrypoint: bash
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-c'
      - |-
        if [ $BRANCH_NAME == "main" ]
        then
          gsutil -m setmeta -r -h 'cache-control: max-age=0,public' 'gs://vizzu-lib-main/*'
        fi
    id: lib_setCacheControl
    waitFor:
      - lib_upload
    entrypoint: bash
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-m'
      - cp
      - '-r'
      - /workspace/example/lib/*
      - 'gs://vizzu-lib-main-sha/lib-$SHORT_SHA'
    id: shalib_upload
    waitFor:
      - desktop_make
      - wasm_make
      - wasm_js_npmRunBuild
timeout: 1800s
options:
  machineType: E2_HIGHCPU_8
