name: CI

on:
  workflow_call:

jobs:

  check_ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: ./tools/docs-check/.venv_vizzu
        key: venv-vizzu-${{ github.run_id }}

    - uses: actions/cache@v3
      with:
        path: ./tools/docs-check/node_modules
        key: nodemodules-vizzu-${{ github.run_id }}

    - name: Touch dev environment
      run: make touch-dev
      working-directory: ./tools/docs-check

    - name: Touch dev-js environment
      run: make touch-dev-js
      working-directory: ./tools/docs-check
          
    - name: Check format
      run: make check-format
      working-directory: ./tools/docs-check

    - name: Check lint
      run: make check-lint
      working-directory: ./tools/docs-check
