name: Init

on:
  workflow_call:

jobs:

  init_dev:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ./tools/docs-check/.venv_vizzu
          key: venv-vizzu-${{ github.run_id }}

      - uses: actions/cache@v3
        with:
          path: ./tools/docs-check/node_modules
          key: nodemodules-vizzu-${{ github.run_id }}

      - name: Init dev environment
        run: make dev
        working-directory: ./tools/docs-check
